apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzcw==  # base64 for 'postgres_pass'
  STREAMLIT_SECRET_KEY: c3RyaW1saXRfc2VjcmV0  # base64 for 'streamlit_secret'
